WebDAV: Fix server closing connection in the middle of long uploads
This fixes the following bug: when uploading a file to the WebDAV
server, if the transfer lasted more than 5 minutes, the request would be
interrupted and fail: "connection reset" on the WebDAV client side, and
in the WebDAV server logs:

    FetchError: request to https://s3.gra.io.cloud.ovh.net/… failed, reason: socket hang up

This is because the default request timeout for Node.JS servers is 5
minutes [^1].

Let's increase it to 15 minutes.

[^1]: https://nodejs.org/api/https.html#serverrequesttimeout